### ISSUE TITLE
Error in downloading the datasets

### ISSUE THREAD

**Issue by ahmadsalimi** [ethanweber/nerfiller#14]
Apparently, some of the dataset files are not available anymore.

When I run the command `python nerfiller/scripts/download.py blender`, I get the following:
```
Traceback (most recent call last):
  File "/home/******/anaconda3/envs/******/lib/python3.10/site-packages/gdown/download.py", line 267, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "/home/******/anaconda3/envs/******/lib/python3.10/site-packages/gdown/download.py", line 55, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 141, in <module>
    entrypoint()
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 137, in entrypoint
    main(tyro.cli(Commands))
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 131, in main
    data_download.download(data_download.save_dir)
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 48, in download
    gdown.download(url, output=str(download_path))
  File "/home/******/anaconda3/envs/******/lib/python3.10/site-packages/gdown/download.py", line 278, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=18JxhpWD-4ZmuFKLzKlAw-w5PpzZxXOcG

but Gdown can't. Please check connections and permissions.
```

And when I try to open the link mentioned in the error log, https://drive.google.com/uc?id=18JxhpWD-4ZmuFKLzKlAw-w5PpzZxXOcG, I get a 404 error.

Also, running `python nerfiller/scripts/download.py meshes` fails with the following error:

```
Traceback (most recent call last):
  File "/home/******/anaconda3/envs/******/lib/python3.10/site-packages/gdown/download.py", line 267, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "/home/******/anaconda3/envs/******/lib/python3.10/site-packages/gdown/download.py", line 55, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 141, in <module>
    entrypoint()
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 137, in entrypoint
    main(tyro.cli(Commands))
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 131, in main
    data_download.download(data_download.save_dir)
  File "/home/******/nerfiller/nerfiller/scripts/download.py", line 67, in download
    gdown.download_folder(url=url, output=str(download_path), quiet=False, use_cookies=False)
  File "/home/******/anaconda3/envs/******/lib/python3.10/site-packages/gdown/download_folder.py", line 325, in download_folder
    local_path = download(
  File "/home/******/anaconda3/envs/******/lib/python3.10/site-packages/gdown/download.py", line 278, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1hb0gIH0DKSexWqUGIYUsZktsrJ5awQrZ

but Gdown can't. Please check connections and permissions.
```

**Comment by ethanweber** [comment]
Hey, I just updated the blender dataset link in Issue #16, which should hopefully fix your issue with the file not being found. Also, sometimes this error will happen where you need to manually go to Google Drive and download the data as per the error message. I believe this is due to quota restrictions of Google Drive. If you follow the code in `nerfiller/scripts/download.py`, that should help with any manual intervention needed.
